### ISSUE TITLE
Could you please provide more details about how to use this tool? Thanks!

### ISSUE THREAD

**Issue by qyx1121** [SandeepKundalwal/Unity-Prefab-PNG-Tool#1]

**Comment by SandeepKundalwal** [comment]
It's straight forward, just import the prefab that you want to capture the png of. Align the camera and check the view of the prefab (tip: split the unity window into scene view and game view, that way you can see the live preview of your prefab) . Click on play. Image will be saved in the root folder.

**Comment by SandeepKundalwal** [comment]
closing the issue.
